### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [LCrandall1/prj-rev-bwfs-tea-cozy#4]
Judging from the combination of structuring your HTML file and the usage of flex box properties, you show understanding on the Flex Box concept. Awesome! Hopefully you will be able to continue using it efficiently for the next and final project! Awesome job on this Tea Cozy project as it looked great on both the code side and the web side!

- Utilization of indentations and whitespace.
- Provided evidence in knowledge of flex box.
- A working navigation bar would've been a great bonus!
- Accurate to design spec.

Overall, superb work! Keep it up!
Grade: Meets expectation.

**Comment by LCrandall1** [comment]
Wow, thank you for the great feedback.  That project was really hard for me and I struggled quite a bit.  I'm glad it shows that I'm making progress :)
